- name: ping the server
  hosts: frontend #connect to win_hostname:
 # required. The hostname to set for the computer

  tasks: 
  - name: Induce an exception to see what happens
    ansible.builtin.ping:
      data: pong