- name: defining data types
  hosts: local
  connection: local
  vars:
    Tool: Ansible
    Duration: 7 Hours
    Platform: Join DevOps
    Learner: Mr. Paint
    
    Topics: # ["Jenkins", "Kubernetes", "Docker", "Ansible"]
      - Jenkins
      - Kubernetes
      - Docker
      - Ansible 

    Concepts:
      Cloud: aws
      Infrastructure: Terraform

  tasks:
  - name: creating data types files
    ansible.builtin.debug:
      msg: tool name is {{ "Tools"}}, Duration is {{ "Duration" }}, Platform is {{ "Platform"}}, Learner is {{ "Learner" }}, Topics are {{ Topics" }}, concepts are {{ "Concepts" }}

